name: Build Master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  use-with-default-settings:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    
    - uses: "./"
      with:
        jdk: zulu@1.8.252

    - name: Print Java version
      run: |
        echo $JAVA_HOME
        echo $PATH
        java -version
      shell: bash

  use-with-custom-java-home-environment-variable:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    
    - uses: "./"
      with:
        jdk: zulu@1.8.252
        javaHomeEnvironmentVariable: ZULU_HOME

    - name: Print Java version
      run: |
        echo $JAVA_HOME
        echo $ZULU_HOME
        echo $PATH
        java -version
      shell: bash

  use-2-javas-with-custom-environment-variable:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    
    - uses: "./"
      with:
        jdk: zulu@1.8.252
        javaHomeEnvironmentVariable: ZULU_HOME

    - uses: "./"
      with:
        jdk: openjdk@1.11.0
        javaHomeEnvironmentVariable: OJ11_HOME

    - name: Print Java version
      run: |
        echo $JAVA_HOME
        echo $ZULU_HOME
        echo $OJ11_HOME
        echo $PATH
        java -version
      shell: bash

  use-without-adding-to-path:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    
    - uses: "./"
      with:
        jdk: zulu@1.8.252
        javaHomeEnvironmentVariable: ZULU_HOME
        addBinDirectoryToPath: false

    - name: Print Java version
      run: |
        echo $JAVA_HOME
        echo $ZULU_HOME
        echo $PATH
        java -version
      shell: bash
